var names = [
    "signal",
    "raise",
    "pipe",
    "dup",
    "dup2",
    "setjmp",
    "sigsetjmp",
    "execve",
    "execvp",
    "execlp",
    "getpwnam",
    "getpwnam_r",
    "tcsetpgrp",
    "kill",
    "killpg",
    "fork",
    "getpid",
    "setpgid",
    "issetugid",
    "strsignal",
    "wait",
    "wait3",
    "wait4",
    "waitpid",
    "sigsuspend",
    "getuid",
    "geteuid",
    "getgid",
    "getegid",
    "umask",
    "getrlimit",
    "setrlimit",
    "sigaction",
    "sigfillset",
    "sigprocmask",
    "sigsetmask",
    "getppid",
    "tcgetpgrp",
    "siginterrupt",
    "gethostname",
    "tzset",
    "flockfile",
    "funlockfile",
    "getpwuid",
    "getpwuid_r",
    "setpwent",
    "endpwent",
    "getgrgid",
    "strmode",
    "acl_get_file",
    "acl_free",
    "acl_get_entry",
    "getprogname",
    "fchdir",
    "fchmod",
    "futimes",
    "utimes",
    "system",
    "mkstemp",
    "mkstemps",
    "mkostemp",
    "mkostemps",
    // curses
    "tgetent",
    "tgetflag",
    "tgetnum",
    "tgetstr",
    "tgoto",
    "tputs",
    // termios
    "cfgetospeed",
    "cfgetispeed",
    "cfsetospeed",
    "cfsetispeed",
    "tcsendbreak",
    "tcdrain",
    "tcflush",
    "tcflow",
    "tcgetsid"
]

const stubs: {
    debug: (message: string) => void,
    [key: string]: (...args: any[]) => void
} = {
    debug: (message) => {}
};
for (let nm of names) {
    stubs[nm] = function() {
        stubs.debug(`stub for ${nm} [${[...arguments]}]`);
    }
}

export default stubs
